import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Travel Pulse - Discover new Places and Create your Memories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="bg-white">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
